/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/3dmodel/scene.gltf -t -r public 
Author: Fatih174 (https://sketchfab.com/Fatih174)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basement-home-office-badeskchallenge-324ceb119c754bed973ab7a603750742
Title: Basement Home Office #BADeskChallenge
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_63: THREE.Mesh;
    Object_64: THREE.Mesh;
    Object_65: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_68: THREE.Mesh;
    Object_69: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_71: THREE.Mesh;
    Object_72: THREE.Mesh;
    Object_73: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_75: THREE.Mesh;
    Object_76: THREE.Mesh;
    Object_77: THREE.Mesh;
    Object_78: THREE.Mesh;
    Object_79: THREE.Mesh;
    Object_80: THREE.Mesh;
    Object_81: THREE.Mesh;
    Object_82: THREE.Mesh;
    Object_83: THREE.Mesh;
    Object_84: THREE.Mesh;
    Object_85: THREE.Mesh;
    Object_86: THREE.Mesh;
    Object_87: THREE.Mesh;
    Object_88: THREE.Mesh;
    Object_89: THREE.Mesh;
    Object_90: THREE.Mesh;
    Object_91: THREE.Mesh;
    Object_92: THREE.Mesh;
    Object_93: THREE.Mesh;
    Object_94: THREE.Mesh;
    Object_95: THREE.Mesh;
    Object_96: THREE.Mesh;
    Object_97: THREE.Mesh;
    Object_98: THREE.Mesh;
    Object_99: THREE.Mesh;
    Object_100: THREE.Mesh;
    Object_101: THREE.Mesh;
    Object_102: THREE.Mesh;
    Object_103: THREE.Mesh;
    Object_104: THREE.Mesh;
    Object_105: THREE.Mesh;
    Object_106: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_108: THREE.Mesh;
    Object_109: THREE.Mesh;
    Object_110: THREE.Mesh;
    Object_111: THREE.Mesh;
    Object_112: THREE.Mesh;
    Object_113: THREE.Mesh;
  };
  materials: {
    ["04_-_CoronaMtl"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    None: THREE.MeshStandardMaterial;
    banner: THREE.MeshStandardMaterial;
    ["banner.001"]: THREE.MeshStandardMaterial;
    ["book.007"]: THREE.MeshStandardMaterial;
    ["book.008"]: THREE.MeshStandardMaterial;
    ["book.009"]: THREE.MeshStandardMaterial;
    ["book.012"]: THREE.MeshStandardMaterial;
    ["cable.2"]: THREE.MeshStandardMaterial;
    canvas: THREE.MeshStandardMaterial;
    clapper_2: THREE.MeshStandardMaterial;
    clapper_3: THREE.MeshStandardMaterial;
    coffee: THREE.MeshStandardMaterial;
    material_41: THREE.MeshStandardMaterial;
    drink: THREE.MeshStandardMaterial;
    ["drink.001"]: THREE.MeshStandardMaterial;
    ["drink.002"]: THREE.MeshStandardMaterial;
    ["drink.003"]: THREE.MeshStandardMaterial;
    fear_the_dark: THREE.MeshStandardMaterial;
    ["fear_the_dark.001"]: THREE.MeshStandardMaterial;
    ["fear_the_dark.002"]: THREE.MeshStandardMaterial;
    floor_wood: THREE.LineBasicMaterial;
    floor_wood: THREE.MeshStandardMaterial;
    lamba: THREE.MeshStandardMaterial;
    lamba_effaf: THREE.MeshStandardMaterial;
    ["mad_max_fury_road_web_by_3ftdeep-d8qr5za"]: THREE.MeshStandardMaterial;
    ["mad_max_fury_road_web_by_3ftdeep-d8qr5za.001"]: THREE.MeshStandardMaterial;
    mausepad: THREE.MeshStandardMaterial;
    monitor_bar: THREE.MeshStandardMaterial;
    mouse: THREE.MeshStandardMaterial;
    obey_the_god: THREE.MeshStandardMaterial;
    paper: THREE.MeshStandardMaterial;
    ["paper.001"]: THREE.MeshStandardMaterial;
    ["paper.002"]: THREE.MeshStandardMaterial;
    ["paper.003"]: THREE.MeshStandardMaterial;
    ["paper.004"]: THREE.MeshStandardMaterial;
    ["paper.005"]: THREE.MeshStandardMaterial;
    pc_glass: THREE.MeshStandardMaterial;
    screen: THREE.MeshStandardMaterial;
    ["screen.001"]: THREE.MeshStandardMaterial;
    ["switch"]: THREE.MeshStandardMaterial;
    trash: THREE.MeshStandardMaterial;
    ["trash.001"]: THREE.MeshStandardMaterial;
    walls: THREE.MeshStandardMaterial;
    ["walls.002"]: THREE.MeshStandardMaterial;
    walls_invis: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    Material_1233: THREE.MeshStandardMaterial;
    book: THREE.MeshStandardMaterial;
    ["book.001"]: THREE.MeshStandardMaterial;
    ["book.002"]: THREE.MeshStandardMaterial;
    ["book.003"]: THREE.MeshStandardMaterial;
    ["book.004"]: THREE.MeshStandardMaterial;
    ["book.005"]: THREE.MeshStandardMaterial;
    ["book.006"]: THREE.MeshStandardMaterial;
    ["book.010"]: THREE.MeshStandardMaterial;
    ["book.011"]: THREE.MeshStandardMaterial;
    book_inside: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    box_2: THREE.MeshStandardMaterial;
    box_3: THREE.MeshStandardMaterial;
    bulp: THREE.MeshStandardMaterial;
    cable: THREE.MeshStandardMaterial;
    ["case"]: THREE.MeshStandardMaterial;
    ["case_.001"]: THREE.MeshStandardMaterial;
    clapper: THREE.MeshStandardMaterial;
    ["clapper_2.001"]: THREE.MeshStandardMaterial;
    coffee_table: THREE.MeshStandardMaterial;
    desk_wood: THREE.MeshStandardMaterial;
    door: THREE.MeshStandardMaterial;
    ["door.001"]: THREE.MeshStandardMaterial;
    fan_led: THREE.MeshStandardMaterial;
    frame: THREE.MeshStandardMaterial;
    ["frame.001"]: THREE.MeshStandardMaterial;
    headphone: THREE.MeshStandardMaterial;
    headphone_snger: THREE.MeshStandardMaterial;
    ["lamba.001"]: THREE.MeshStandardMaterial;
    ["lamba.2"]: THREE.MeshStandardMaterial;
    lambaa: THREE.MeshStandardMaterial;
    material_63: THREE.MeshStandardMaterial;
    monitor_1: THREE.MeshStandardMaterial;
    neon_sign: THREE.MeshStandardMaterial;
    sofa: THREE.MeshStandardMaterial;
    speaker_2: THREE.MeshStandardMaterial;
    tape: THREE.MeshStandardMaterial;
    ["walls.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/3dmodel/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.413}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["04_-_CoronaMtl"]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Material.019"]}
        />
        <mesh geometry={nodes.Object_6.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.banner} />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["banner.001"]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["book.007"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["book.008"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["book.009"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["book.012"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["cable.2"]}
        />
        <mesh geometry={nodes.Object_14.geometry} material={materials.canvas} />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.clapper_2}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.clapper_3}
        />
        <mesh geometry={nodes.Object_17.geometry} material={materials.coffee} />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.material_41}
        />
        <mesh geometry={nodes.Object_19.geometry} material={materials.drink} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.drink} />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["drink.001"]}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials["drink.002"]}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials["drink.003"]}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.fear_the_dark}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials["fear_the_dark.001"]}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials["fear_the_dark.002"]}
        />
        <lineSegments
          geometry={nodes.Object_27.geometry}
          material={materials.floor_wood}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.floor_wood}
        />
        <mesh geometry={nodes.Object_29.geometry} material={materials.lamba} />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.lamba_effaf}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials["mad_max_fury_road_web_by_3ftdeep-d8qr5za"]}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials["mad_max_fury_road_web_by_3ftdeep-d8qr5za.001"]}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials.mausepad}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials.monitor_bar}
        />
        <mesh geometry={nodes.Object_35.geometry} material={materials.mouse} />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.obey_the_god}
        />
        <mesh geometry={nodes.Object_37.geometry} material={materials.paper} />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials["paper.001"]}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials["paper.002"]}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials["paper.003"]}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials["paper.004"]}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials["paper.005"]}
        />
        <mesh
          geometry={nodes.Object_43.geometry}
          material={materials.pc_glass}
        />
        <mesh geometry={nodes.Object_44.geometry} material={materials.screen} />
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials["screen.001"]}
        />
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials["switch"]}
        />
        <mesh geometry={nodes.Object_47.geometry} material={materials.trash} />
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials["trash.001"]}
        />
        <mesh geometry={nodes.Object_49.geometry} material={materials.walls} />
        <mesh
          geometry={nodes.Object_50.geometry}
          material={materials["walls.002"]}
        />
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials.walls_invis}
        />
        <mesh
          geometry={nodes.Object_52.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_53.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Object_54.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          geometry={nodes.Object_56.geometry}
          material={materials.Material_1233}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials.Material_1233}
        />
        <mesh
          geometry={nodes.Object_58.geometry}
          material={materials.Material_1233}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.Material_1233}
        />
        <mesh geometry={nodes.Object_60.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.book} />
        <mesh
          geometry={nodes.Object_62.geometry}
          material={materials["book.001"]}
        />
        <mesh
          geometry={nodes.Object_63.geometry}
          material={materials["book.002"]}
        />
        <mesh
          geometry={nodes.Object_64.geometry}
          material={materials["book.003"]}
        />
        <mesh
          geometry={nodes.Object_65.geometry}
          material={materials["book.004"]}
        />
        <mesh
          geometry={nodes.Object_66.geometry}
          material={materials["book.005"]}
        />
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials["book.006"]}
        />
        <mesh
          geometry={nodes.Object_68.geometry}
          material={materials["book.010"]}
        />
        <mesh
          geometry={nodes.Object_69.geometry}
          material={materials["book.011"]}
        />
        <mesh
          geometry={nodes.Object_70.geometry}
          material={materials.book_inside}
        />
        <mesh
          geometry={nodes.Object_71.geometry}
          material={materials.material}
        />
        <mesh geometry={nodes.Object_72.geometry} material={materials.box_2} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.box_3} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.bulp} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.cable} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.cable} />
        <mesh
          geometry={nodes.Object_77.geometry}
          material={materials["case"]}
        />
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials["case"]}
        />
        <mesh
          geometry={nodes.Object_79.geometry}
          material={materials["case_.001"]}
        />
        <mesh
          geometry={nodes.Object_80.geometry}
          material={materials.clapper}
        />
        <mesh
          geometry={nodes.Object_81.geometry}
          material={materials["clapper_2.001"]}
        />
        <mesh
          geometry={nodes.Object_82.geometry}
          material={materials.coffee_table}
        />
        <mesh
          geometry={nodes.Object_83.geometry}
          material={materials.desk_wood}
        />
        <mesh geometry={nodes.Object_84.geometry} material={materials.door} />
        <mesh
          geometry={nodes.Object_85.geometry}
          material={materials["door.001"]}
        />
        <mesh
          geometry={nodes.Object_86.geometry}
          material={materials.fan_led}
        />
        <mesh geometry={nodes.Object_87.geometry} material={materials.frame} />
        <mesh
          geometry={nodes.Object_88.geometry}
          material={materials["frame.001"]}
        />
        <mesh
          geometry={nodes.Object_89.geometry}
          material={materials.headphone}
        />
        <mesh
          geometry={nodes.Object_90.geometry}
          material={materials.headphone}
        />
        <mesh
          geometry={nodes.Object_91.geometry}
          material={materials.headphone}
        />
        <mesh
          geometry={nodes.Object_92.geometry}
          material={materials.headphone_snger}
        />
        <mesh geometry={nodes.Object_93.geometry} material={materials.lamba} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.lamba} />
        <mesh
          geometry={nodes.Object_95.geometry}
          material={materials["lamba.001"]}
        />
        <mesh
          geometry={nodes.Object_96.geometry}
          material={materials["lamba.001"]}
        />
        <mesh
          geometry={nodes.Object_97.geometry}
          material={materials["lamba.001"]}
        />
        <mesh
          geometry={nodes.Object_98.geometry}
          material={materials["lamba.2"]}
        />
        <mesh geometry={nodes.Object_99.geometry} material={materials.lambaa} />
        <mesh
          geometry={nodes.Object_100.geometry}
          material={materials.material_63}
        />
        <mesh
          geometry={nodes.Object_101.geometry}
          material={materials.monitor_1}
        />
        <mesh
          geometry={nodes.Object_102.geometry}
          material={materials.monitor_1}
        />
        <mesh
          geometry={nodes.Object_103.geometry}
          material={materials.monitor_bar}
        />
        <mesh
          geometry={nodes.Object_104.geometry}
          material={materials.neon_sign}
        />
        <mesh
          geometry={nodes.Object_105.geometry}
          material={materials.neon_sign}
        />
        <mesh
          geometry={nodes.Object_106.geometry}
          material={materials.neon_sign}
        />
        <mesh
          geometry={nodes.Object_107.geometry}
          material={materials.neon_sign}
        />
        <mesh
          geometry={nodes.Object_108.geometry}
          material={materials.neon_sign}
        />
        <mesh
          geometry={nodes.Object_109.geometry}
          material={materials.neon_sign}
        />
        <mesh geometry={nodes.Object_110.geometry} material={materials.sofa} />
        <mesh
          geometry={nodes.Object_111.geometry}
          material={materials.speaker_2}
        />
        <mesh geometry={nodes.Object_112.geometry} material={materials.tape} />
        <mesh
          geometry={nodes.Object_113.geometry}
          material={materials["walls.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3dmodel/scene.gltf");
